eno=(input("enter the employee number: "))
ename=(input("enter the employee name: "))
esal=(input("enter the employee salary: "))
eaddr=(input("enter the employee addresss: "))
married=(input("is employee married?[True/False]: "))

print("Please confirm your provided information ")
print("employee number:",eno)
print("employee name:",ename)
print("employee salary:",esal)
print("employee address:",eaddr)